<a href="https://colab.research.google.com/github/NILESH-SH/AIML/blob/main/Lab_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
a = np.array([9,2,3])
b = np.array([5,6,7.5])
c = a+b
# print(a,b)
c.sort()
print(c)


[ 8.  10.5 14. ]


In [ ]:
d = np.array([[1,2,3],[4,5,6]])
f = np.array([[8,9,3],[4,5,6]])
e = d*f
e


array([[ 8, 18,  9],
       [16, 25, 36]])

In [ ]:
z = np.zeros((3,4))
o = np.ones((2,3))
print(z,o)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] [[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#generate a list with given number gap and last number is not included
g = np.arange(1,10,2)
print(g)

[1 3 5 7 9]


In [ ]:
#generate a list with equal gap
l = np.linspace(1,2,5)
print(l)

[1.   1.25 1.5  1.75 2.  ]


In [ ]:
f = np.full((2,2),7)
print(f)

[[7 7]
 [7 7]]


In [ ]:
e = np.eye(5,dtype=int)
print(e)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [ ]:
r = np.random.random((3,4))
print(r)

[[0.54678173 0.8200867  0.2112748  0.83341348]
 [0.94992359 0.76197681 0.19112129 0.93847345]
 [0.03319463 0.20435255 0.58239079 0.30254337]]
