<a href="https://colab.research.google.com/github/NILESH-SH/AIML/blob/main/SVM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:

import numpy as np
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
X = np.array([[1, 2], [2, 3], [3, 1], [4, 3], [5, 3], [6, 2]])
y = np.array([0, 0, 0, 1, 1, 1])

svm_classifier = SVC(kernel='linear')

svm_classifier.fit(X, y)
X_test = np.array([[2, 2], [4, 2], [5, 4]])
y_test = np.array([0, 1, 1])

y_pred = svm_classifier.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

print("\nSupport Vectors:")
print(svm_classifier.support_vectors_)

print("\nSupport Vector Indices:")
print(svm_classifier.support_)

print("\nNumber of Support Vectors for each class:")
print(svm_classifier.n_support_)

print("\nIntercept:")
print(svm_classifier.intercept_)

print("\nCoefficients of the support vector in the decision function:")
svm_classifier.coef_

Accuracy: 1.0

Support Vectors:
[[2. 3.]
 [3. 1.]
 [4. 3.]]

Support Vector Indices:
[1 2 3]

Number of Support Vectors for each class:
[2 1]

Intercept:
[-4.50112]

Coefficients of the support vector in the decision function:


array([[1.     , 0.50048]])